# Generated by Django 6.0.2 on 2026-03-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_completed_subcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
