# Generated by Django 6.0.2 on 2026-02-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon_class',
            field=models.CharField(default='bi-code-slash', max_length=50),
        ),
    ]
