# Generated by Django 6.0.2 on 2026-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_subject_description_remove_subject_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='icon_class',
            field=models.CharField(default='bi-journal-text', max_length=50),
        ),
    ]
