# Generated by Django 6.0.2 on 2026-03-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quizsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
