# Generated by Django 6.0.2 on 2026-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_quizattempt_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_questions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
